### ISSUE TITLE
Some props are not set

### ISSUE THREAD

**Issue by giulioz** [pmndrs/react-three-flex#35]
Like alignSelf and alignContent

**Comment by talentlessguy** [comment]
Will look into this

**Comment by chasedavis** [comment]
+1 -- can't seem to alignContent on 0.5.2. this would be a great one to fix.

**Comment by saitonakamura** [comment]
Do I understand correctly that this should be fixed in https://github.com/pmndrs/react-three-flex/blob/1f44bad9080f7f5426b93d84e9fbe7937dc28cdf/src/util.ts#L9 ?

**Comment by talentlessguy** [comment]
hey guys I just merged the PR with a fix will release a new version soon
