### ISSUE TITLE
typescript errors with r3f v8

### ISSUE THREAD

**Issue by oveddan** [pmndrs/react-three-flex#78]
Related to  [issue #2190 in r3f](https://github.com/pmndrs/react-three-fiber/issues/2190#issuecomment-1089246649)

**Comment by oveddan** [comment]
When upgrading react three fiber to v8 and above, `Box` asks you to now define `attachArray={undefined} attachObject={undefined} attachFns={undefined}` or else you get a typescript error:

```jsx
return (
        <Box attachArray={undefined} attachObject={undefined} attachFns={undefined}>
          {children}
        </Box>
      );
```

**Comment by oveddan** [comment]
I believe flex needs to upgrade to support the new attach api?

**Comment by saitonakamura** [comment]
Yeah. I think so. Would be a major release

**Comment by giulioz** [comment]
Potential fix on https://github.com/pmndrs/react-three-flex/pull/79
